import { createHash } from "node:crypto";
import { mkdir, readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { z } from "zod";

import { writeFileAtomically } from "../contracts/atomic-file.js";
import { classifyLocalSensitivity } from "../contracts/sensitivity.js";
import { openRuntimeDatabase } from "../runtime/database.js";

const countsSchema = z.object({
  reviewSuggestions: z.number().int().nonnegative(),
  humanConflicts: z.number().int().nonnegative(),
  verificationRequests: z.number().int().nonnegative(),
  modelHealthIncidents: z.number().int().nonnegative(),
  sensitivityFindings: z.number().int().nonnegative(),
  deadLetters: z.number().int().nonnegative()
});

export interface ReviewInboxView {
  readonly schemaVersion: 1;
  readonly state: "generated";
  readonly path: string;
  readonly generatedAt: string;
  readonly contentSha256: string;
  readonly counts: z.infer<typeof countsSchema>;
}

function safeBounded(value: unknown, maximum = 512): string {
  if (typeof value !== "string" || value.trim().length === 0) return "Not provided";
  const bounded = value.trim().slice(0, maximum);
  const sensitivity = classifyLocalSensitivity(bounded);
  return sensitivity.state === "normal"
    ? bounded.replaceAll("\n", " ")
    : `[redacted: ${sensitivity.category}]`;
}

function memoryLink(row: Record<string, unknown>): string {
  const memoryId = z.string().parse(row.target_memory_id);
  if (row.scope_kind === "global") {
    return `[[Memories/Global/${memoryId}|${memoryId}]]`;
  }
  if (row.scope_kind === "project" && typeof row.project_id === "string") {
    return `[[Memories/Projects/${row.project_id}/${memoryId}|${memoryId}]]`;
  }
  return `\`${memoryId}\``;
}

function sha256(source: string): string {
  return createHash("sha256").update(source).digest("hex");
}

export async function generateReviewInbox(request: {
  readonly runtimeRoot: string;
  readonly vaultRoot: string;
  readonly generatedAt: string;
}): Promise<ReviewInboxView> {
  const generatedAt = z.iso.datetime().parse(request.generatedAt);
  const runtimeRoot = resolve(request.runtimeRoot);
  const vaultRoot = resolve(request.vaultRoot);
  const database = await openRuntimeDatabase(runtimeRoot);
  let suggestions: readonly Record<string, unknown>[];
  let conflicts: readonly Record<string, unknown>[];
  let verificationRequests: readonly Record<string, unknown>[];
  let incidents: readonly Record<string, unknown>[];
  let findings: readonly Record<string, unknown>[];
  let deadLetters: readonly Record<string, unknown>[];
  try {
    suggestions = database.prepare(
      `SELECT suggestion.*, catalog.scope_kind, catalog.project_id
       FROM governance_review_suggestions AS suggestion
       LEFT JOIN memory_catalog AS catalog
         ON catalog.memory_id = suggestion.target_memory_id
       WHERE suggestion.state = 'open'
       ORDER BY suggestion.created_at, suggestion.suggestion_id`
    ).all();
    conflicts = database.prepare(
      `SELECT conflict_id, proposed_memory_id, conflicting_memory_ids_json,
              scope_kind, project_id, detected_by, created_at
       FROM human_memory_conflicts WHERE state = 'open'
       ORDER BY created_at, conflict_id`
    ).all();
    verificationRequests = database.prepare(
      `SELECT request.verification_request_id, request.candidate_id,
              request.description, request.proposed_action, request.created_at,
              candidate.project_id
       FROM verification_requests AS request
       JOIN memory_candidates AS candidate ON candidate.candidate_id = request.candidate_id
       WHERE request.state = 'open'
       ORDER BY request.created_at, request.verification_request_id`
    ).all();
    incidents = database.prepare(
      `SELECT incident_id, state, reason_category, started_at, last_failure_at
       FROM model_health_incidents WHERE state != 'recovered'
       ORDER BY started_at, incident_id`
    ).all();
    findings = database.prepare(
      `SELECT finding_id, state, category, first_seen_at, last_seen_at, occurrence_count
       FROM sensitivity_findings WHERE state = 'quarantined'
       ORDER BY first_seen_at, finding_id`
    ).all();
    deadLetters = database.prepare(
      `SELECT event_id, last_error_code, updated_at
       FROM capture_events WHERE state = 'dead_letter'
       ORDER BY updated_at, event_id`
    ).all();
  } finally {
    database.close();
  }
  const counts = {
    reviewSuggestions: suggestions.length,
    humanConflicts: conflicts.length,
    verificationRequests: verificationRequests.length,
    modelHealthIncidents: incidents.length,
    sensitivityFindings: findings.length,
    deadLetters: deadLetters.length
  };
  const lines = [
    "<!-- Generated by MemStore. Rebuild this view instead of editing it. -->",
    "# MemStore Review Inbox",
    "",
    `Generated: ${generatedAt}`,
    "",
    "This is a body-free operational view. Edit authoritative Memory in its source note.",
    "",
    "## Human Memory Review Suggestions",
    ""
  ];
  if (suggestions.length === 0) lines.push("_None._", "");
  for (const row of suggestions) {
    lines.push(
      `- ${memoryLink(row)} — **${safeBounded(row.suggestion_kind, 64)}**`,
      `  - Suggestion: \`${safeBounded(row.suggestion_id, 128)}\``,
      `  - Reason: ${safeBounded(row.reason)}`,
      `  - Evidence refs: ${safeBounded(row.evidence_refs_json)}`,
      `  - Created: ${safeBounded(row.created_at, 64)}`
    );
  }
  lines.push("", "## Human Conflicts", "");
  if (conflicts.length === 0) lines.push("_None._", "");
  for (const row of conflicts) {
    lines.push(
      `- Conflict \`${safeBounded(row.conflict_id, 128)}\``,
      `  - Proposed Memory: \`${safeBounded(row.proposed_memory_id, 128)}\``,
      `  - Conflicting identities: ${safeBounded(row.conflicting_memory_ids_json)}`,
      `  - Project: ${safeBounded(row.project_id, 128)}`,
      `  - Detected by: ${safeBounded(row.detected_by, 128)}`,
      `  - Created: ${safeBounded(row.created_at, 64)}`
    );
  }
  lines.push("", "## Verification Requests", "");
  if (verificationRequests.length === 0) lines.push("_None._", "");
  for (const row of verificationRequests) {
    lines.push(
      `- Request \`${safeBounded(row.verification_request_id, 128)}\``,
      `  - Candidate: \`${safeBounded(row.candidate_id, 128)}\``,
      `  - Project: ${safeBounded(row.project_id, 128)}`,
      `  - Evidence gap: ${safeBounded(row.description)}`,
      `  - Suggested action: ${safeBounded(row.proposed_action)}`,
      `  - Created: ${safeBounded(row.created_at, 64)}`
    );
  }
  lines.push("", "## Operational Incidents", "");
  const operational = [...incidents, ...findings, ...deadLetters];
  if (operational.length === 0) lines.push("_None._", "");
  for (const row of incidents) {
    lines.push(`- Model incident \`${safeBounded(row.incident_id, 128)}\`: ${safeBounded(row.state, 32)} / ${safeBounded(row.reason_category, 64)}`);
  }
  for (const row of findings) {
    lines.push(`- Sensitivity finding \`${safeBounded(row.finding_id, 128)}\`: ${safeBounded(row.category, 64)} (body not retained)`);
  }
  for (const row of deadLetters) {
    lines.push(`- Dead letter \`${safeBounded(row.event_id, 128)}\`: ${safeBounded(row.last_error_code, 64)}`);
  }
  const source = `${lines.join("\n").trimEnd()}\n`;
  const finalSensitivity = classifyLocalSensitivity(source);
  if (finalSensitivity.state !== "normal") {
    throw new Error("Generated Review Inbox failed the local body-free sensitivity gate.");
  }
  const path = join(vaultRoot, "_MemStore", "Review Inbox.md");
  await mkdir(dirname(path), { recursive: true, mode: 0o700 });
  await writeFileAtomically(path, source, 0o600);
  const contentSha256 = sha256(source);
  const stateDatabase = await openRuntimeDatabase(runtimeRoot);
  try {
    stateDatabase.prepare(
      `INSERT INTO review_inbox_state(
         singleton, generated_at, content_sha256, item_counts_json, path
       ) VALUES (1, ?, ?, ?, ?)
       ON CONFLICT(singleton) DO UPDATE SET
         generated_at = excluded.generated_at,
         content_sha256 = excluded.content_sha256,
         item_counts_json = excluded.item_counts_json,
         path = excluded.path`
    ).run(generatedAt, contentSha256, JSON.stringify(counts), path);
  } finally {
    stateDatabase.close();
  }
  return { schemaVersion: 1, state: "generated", path, generatedAt, contentSha256, counts };
}

export async function inspectReviewInbox(request: {
  readonly runtimeRoot: string;
  readonly vaultRoot: string;
}): Promise<ReviewInboxView | undefined> {
  const database = await openRuntimeDatabase(request.runtimeRoot);
  let row: Record<string, unknown> | undefined;
  try {
    row = database.prepare("SELECT * FROM review_inbox_state WHERE singleton = 1").get();
  } finally {
    database.close();
  }
  if (row === undefined) return undefined;
  const path = z.string().parse(row.path);
  const expectedPath = join(resolve(request.vaultRoot), "_MemStore", "Review Inbox.md");
  if (resolve(path) !== expectedPath) throw new Error("Review Inbox path is outside the configured Vault.");
  const source = await readFile(path, "utf8");
  const contentSha256 = z.string().parse(row.content_sha256);
  if (sha256(source) !== contentSha256) throw new Error("Review Inbox content identity changed.");
  return {
    schemaVersion: 1,
    state: "generated",
    path,
    generatedAt: z.iso.datetime().parse(row.generated_at),
    contentSha256,
    counts: countsSchema.parse(JSON.parse(z.string().parse(row.item_counts_json)))
  };
}
